version: '3.7'

name: postgres

services:
  postgres:
    image: postgis/postgis:latest
    container_name: postgres
    environment:
        POSTGRES_DB: database
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    ports:
      -  5432:5432
    volumes:
      -  postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: postgres
