version: '3.7'

name: sparknotebook

services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: spark
    volumes:
      -  "../../jupyter:/home/jovyan/jupyter"
      -  ../../data:/home/jovyan/data
    ports:
      -  8888:8888
    command: ["start.sh jupyter notebook --NotebookApp.token=''"]
