version: '3.7'

name: neo4jlocal

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      -  7474:7474
      -  7687:7687
    environment:
      NEO4J_AUTH: none
    volumes:
      -  neo4j:/data
      
volumes:
   neo4j:
     name: neo4j
